language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - node
  - lts/*
script:
  - npm run test:coverage
  - npm run build:ci
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
